### ISSUE TITLE
Modal Effective Mass

### ISSUE THREAD

**Issue by yalnte** [nasa/NASTRAN-95#12]
Does anyone know how modal effective masses were calculated when using NASTRAN95 please?

Looking at various sources from around this time it looks like it can only be done with a bit of DMAP?

If that's the case does anyone know how the rigid body displacements can be calculated automatically?
I think more modern versions use the **VECPLOT** DMAP module to do this:

> Performs utility functions on g-set size matrices, including computation of resultants, transformation from one coordinate system to another, and generation of rigid body matrices.

**Comment by yalnte** [comment]
For anyone tracking this / completeness the following method is useful and has DMAP PDF attached (but still seems to require **VECPLOT**)

https://www.researchgate.net/post/How_can_I_estimate_modal_participation_factor_from_mode_mass_normalized_in_CEASER_II

**Comment by JuanP74** [comment]
I guess this is the answer to your question https://ntrs.nasa.gov/citations/19840007531
maybe it needs some update...

**Comment by yalnte** [comment]
Thanks, I saw this but read the comment:

> The third -part of the DMAP alter calculates the diagonal terms of the modal mass matrix These can only be calculated in the MSC version since they require 1 feature in the DIAGONAL module (namely raising all elements of a matrix to a power) not available in the COSMIC DIAGONAL module.

**Comment by JuanP74** [comment]
the paper is from 1984...if you check latest COSMIC NASTRAN DMAP user manual (.../um/DMAP.TXT):

> DIAGONAL - Strip Diagonal From Matrix
> 
> Purpose
> 
> To remove the real part of the diagonal from a matrix, raise each term to a
> specified power, and output a column vector, a square symmetric matrix, or a
> diagonal matrix.
> 
> DMAP Calling Sequence
> 
> DIAGONAL A/B/C,Y,OPT=COLUMN/V,Y,POWER=1. $

details are in subroutine DIAGON in file diagon.f, needs further checking; first try the example in the paper. Otherwise you should modify diagon.f which does not seem extremely complex.

**Comment by JuanP74** [comment]
Hi,
I have modified the ALTER to achieve same results as in above paper. Solution is not very elegant, neither very efficient but will do the job in most situations. Maybe someone will improve it.

BR,

JP.

Attached the cosmic nastran input deck with modified alter for sol 3 (remove .txt extension).
[dmapbase.bdf.txt](https://github.com/nasa/NASTRAN-95/files/5079169/dmapbase.bdf.txt)

**Comment by yalnte** [comment]
Hi, thanks very much for this. Have tried in a non-trivial example and seems to work. Apologies for long time in responding!
