### ISSUE TITLE
Why plt file is empty?

### ISSUE THREAD

**Issue by ghost** [nasa/NASTRAN-95#17]
After solving a case, I got the result in F06 file. But the plt file is always empty. What is the setting to output result into plt file? 
Which FORTRAN subroutine writes result into F06 file?
Thanks.

**Comment by JuanP74** [comment]
you need to have XYPLOT commands in the input deck so there is something in the .plt file...The `/usr/bin/nastran` batch file creates it even if there is nothing sent to the .plt file because the nastran script is very basic.
See chapter 4 of Nastran User's Manual VOL. 1 for plotting nastran instructions.
When you get the .plt file you have to postprocess it with nastplot utility to get a postcript file...for me so far unsuccessfully.

**Comment by ghost** [comment]
> When you get the .plt file you have to postprocess it with nastplot utility to get a postcript file...for me so far unsuccessfully.

I found an example - d11011a.inp,  Its first line is 
`NASTRAN FILES=(NPTP,PLT2) `
And later has these code:
`PLOTID = NASTRAN DEMONSTRATION PROBLEM NO. D11-01-1A        
                    
OUTPUT(XYOUT)           
                                                        
PLOTTER = NASTPLT     
                                                          
        CAMERA = 3      
                                                        
        SKIP BETWEEN FRAMES = 1          
                                       
        XGRID LINE = YES    
                                                    
        YGRID LINE = YES        
                                                
     XTITLE =                       FREQUENCY (HERTZ)           
                
     YTITLE = S     
                                                            
     TCURVE = POWER SPECTRAL DENSITY OF POINT 6  DISPLACEMENT        
           
   XYPLOT,XYPRINT DISP PSDF /  6(T3)          
                                  
$                 
                                                              
     TCURVE = POWER SPECTRAL DENSITY OF POINT 6 ACCELERATION      
              
   XYPLOT ACCELERATION PSDF / 6(T3) 
                                            
$                                                         
                      
     XTITLE =                      TIME LAG (SECONDS)               
            
     YTITLE = R             
                                                    
     TCURVE = AUTOCORRELATION FUNCTION FOR POINT 6  DISPLACEMENT         
       
   XYPLOT,XYPRINT DISP AUTO /  6(T3)     `

I got something in plt file. When run nastplot, It only accepts plt1 or plt2 file. I renamed the plt to plt1 file. Not working. Then I renamed it to plt2 file, because the first line of inp says plt2. It worked. I have to choose  VAX/POSTSCRIPT  and I got a d11011a.p file.  Open it with a text editor, there are a lot lines like this:
`********** moveto

********** lineto`

I'll find a ps reader to see if I could get some drawing.

**Comment by JuanP74** [comment]
what I meant by "unsuccessfully" is that the .p file does not work. If you convert it using ps2pdf it will issue an error, since the ***** in the .p file should be numbers. I haven't found a combination that creates a valid .p file.

**Comment by ghost** [comment]
I am reading the um/PLOT.TXT file. There is one section is:
`4.4  NASTRAN GENERAL PURPOSE PLOTTER (NASTPLT) FILE`
It says:
`Each record of the NASTPLT file is composed of 100 plot commands, each command being composed of 30 bytes`. 
It looks right after each 100X3 bytes, there is '0d 0a' to separate each record. But looking into each command, seems the last 8 bytes not all zero. 

`P C R4 R3 R2 R1 R0 S4 S3 S2 S1 S0 T4 T3 T2 T1 T0 U4 U3 U2 U1 U0 00000000`
1+1+5X4+8=30 bytes total.

**Comment by ghost** [comment]
Is there a link for User's Manual VOL. 1? Thanks.

**Comment by JuanP74** [comment]
I think I got it from the freeBSD distribution of NASTRAN 95. However here you have a link to it in its latest revision (08) available as a document: https://www.abbottaerospace.com/downloads/nasa-sp-22208-vol-i-nastran-users-manual-vol-i/
The TXT files in the um folder are a newer revision of it (um stands as user manual) specially relevant for software evolution.

**Comment by JuanP74** [comment]
If you download the tar file here in doc folder you have all four PDF files, 2 user manuals, programmer manual and theoretical manual

https://www.freshports.org/cad/NASTRAN-95/

**Comment by ghost** [comment]
Thanks. Why they only release vol II here? Is there any other vol except vol I & II? Yes, the um folder is very important. The nasthelp program is pretty handy to use. Easy to search with keyword.

**Comment by JuanP74** [comment]
Hi there. I think it is considered that the .TXT files are the latest release of Vol. 1, but I prefer the pdf even if it's a bit outdated. There aren't any other program volumens as described in INTR.txt "The User's Manual is one of four manuals that constitute the documentation for NASTRAN, the other three being the Theoretical Manual, the Programmer's Manual, and the Demonstration Problem Manual." The demonstration manual is NASA SP-224 report but is the same as the demonstration .inp files you find in ../inp/ folder with the outputs in /demoout/ (there is as well the theoretical explanation in /inp/ folder, .txt files.

Regarding nastplot, I checked the code a bit (I'm not a programmer so a bit difficult for me) and at subroutine PSLINE you have the format with label 2000 expecting 2I5 numbers and if you write them to the screen with write (*,*) these are 6 digit numbers, hence the *****. I am not sure at this moment if the .plt2 file is properly generated or if the issue is with nastplot because for the demo file you chose there should be 3 plots, and nastplot only finds 1 and then EOF. Keep working on it a bit, but not my main interest since these days nastran plotter is seldom used

**Comment by ghost** [comment]
I changed 2I5 to 2I10, and got numbers now. But they are all the same. Before it, the R S T U value must be wrong somewhere.

**Comment by JuanP74** [comment]
Hi, I found this paper, but still do not know how to produce a PLT1 file. https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19910011194.pdf

**Comment by ghost** [comment]
Put this line as the first line of an inp file. 

`NASTRAN FILES=PLT1`

I have successfully read a plt1 file and draw the plot by my program.

Do you have success of running the substracting windmill case? Issue #10

**Comment by JuanP74** [comment]
Right, just did it. I do not understand well because yesterday I think did the same in another computer and didn't work...Thanks.
You wrote a new program to read the plt1 files? or with nastplot? I will try with the basic code...
I'll try the windmill case later and tell you about the outcome.

**Comment by ghost** [comment]
A new program. It's easy to write with VB.net. Also I am not into ps file.

**Comment by JuanP74** [comment]
hi,
I typed the basic code and run in in [pcbasic](http://robhagemans.github.io/pcbasic/doc/1.2/#pc-basic) and it works! I let it here attached together with the pictures.

remove .txt extension before running it. I checked this is the right result.
[nasplot .bas.txt](https://github.com/nasa/NASTRAN-95/files/4999435/nasplot.bas.txt)

I'll try to see if people working on pyNASTRAN is interested in adding this kind of posprocessing to their software.


![plot1 - plot no  1 - d11011a](https://user-images.githubusercontent.com/60241377/88892060-7cb3f900-d244-11ea-9174-19cc2e70eb94.png)

![plot1 - plot no  2 - d11011a](https://user-images.githubusercontent.com/60241377/88892059-7c1b6280-d244-11ea-930f-1852b6e5a70d.png)

![plot1 - plot no  3 - d11011a](https://user-images.githubusercontent.com/60241377/88892054-7aea3580-d244-11ea-83d6-898e0ffaad65.png)

Addendum, 13th Dec 2020: I have created a fortran version that processes the PLT1 ascii files from nastran and creates a postscript file that can later be converted to pdf using ps2pdf utility, acrobat distiller, etc. Attached the fortran code and pdf examples.


[nastplot1.for.txt](https://github.com/nasa/NASTRAN-95/files/5684998/nastplot1.for.txt)

[d11011a.plt1.pdf](https://github.com/nasa/NASTRAN-95/files/5685000/d11011a.plt1.pdf)
[d01021a.plt.pdf](https://github.com/nasa/NASTRAN-95/files/5685001/d01021a.plt.pdf)
[t16011a.plt.pdf](https://github.com/nasa/NASTRAN-95/files/5685002/t16011a.plt.pdf)

**Comment by ghost** [comment]
Yes, that's it.
