### ISSUE TITLE
Error running large problem

### ISSUE THREAD

**Issue by JuanP74** [nasa/NASTRAN-95#18]
Hi, I tried to run a large problem available from freeBSD distribution of NASTRAN-95. It runs and completes the eigenvalue extraction but seems to fail when writing the results in the output file. Anyone has a clue about what could be the problem?

Input and output files attached in a zip file.

Running latest nastran distribution of Ubuntu.
[large_problem3.zip](https://github.com/nasa/NASTRAN-95/files/5006799/large_problem3.zip)

Regards.

**Comment by ghost** [comment]
*** ERROR OCCURRED IN PAKUNPK I/O SUBSYSTEM ***

This is print out in mds/dsmsg1.f
There are a few files call this sub. 
mds/pack.f is one of them.


No idea.

**Comment by ghost** [comment]
Is there any description of the case? Seems Pload4 on all CQUAD4s.

**Comment by JuanP74** [comment]
hi,
 in fact the case is a modes analysis (SOL 3) so only constraints are used but there is a load case defined for use in statics (SOL 1) which is constant pressure (PLOAD4) in all outer shell of the 1/8 thick spherical shell (made of solid elements CIHEX1 plus a layer of CQUAD4 shells in the outer surface).
It is relatively easy to use gmsh to visualize models and results using txt files as it can represent scalar, vector and tensor results and create results that are loads or constraints. Nastran mesh (only mesh) is directly read by the software (MSC format, so sometimes small changes are required in the input file for visualization purposes): http://gmsh.info/doc/texinfo/gmsh.html#Legacy-formats

**Comment by ghost** [comment]
Don't know gmsh could read nastran case file. Thanks.

How do I get GRID in F06 file? There is no S O R T E D   B U L K    D A T A    E C H O section. How do I switch it on?

**Comment by JuanP74** [comment]
echo is controlled by the key `ECHO` in case control deck, which is the input deck section between the `CEND` and the `BEGIN BULK `cards. Default is `ECHO = SORT` so either you comment ($) the `ECHO = NONE` card or change it to `ECHO = SORT`.

**Comment by JuanP74** [comment]
fixed, see issue #11
